apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: nginx-new
spec:
  upstream:
    repo: nginx-new
    package: nginx-new
    revision: v1
  targets:
  - objectSelector:
      apiVersion: infra.nephio.org/v1alpha1
      kind: WorkloadCluster
      matchLabels:
        nephio.org/site-type: regional
    template:
      downstream:
        package: nginx-new
      annotations:
        approval.nephio.org/policy: initial
      injectors:
      - nameExpr: regional
